# Initiating a matrix
We can initiate a matrix using the matrix() function with parameters:
  
* data: the data included in the matrix. If left blank, the default is NA
* nrow: the desired number of rows in the matrix. If left blank, the default is 1
* ncol: the desired number of columns in the matrix. If left blank, the default is


In [1]:
# If data is a single value, the matrix will simply be a matrix of that value. For example:
ones <- matrix(data = 1, nrow = 2, ncol = 3)
ones

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1

In [2]:
# If data is a vector, the default process for matrices is to fill down columns. For example:
c_d <- matrix(data = c("c", "d"), nrow = 2, ncol = 3)
c_d

[,1] [,2] [,3]
[1,] c    c    c   
[2,] d    d    d

We can see here that the first column has the vector values of a then b. This vector repeats in the next open space, which in this case is the first value of the second column. If the vector in data does not evenly fit down a column, the data will repeat itself until all spots are filled. For example:

In [20]:
abc <- matrix(data = c("a", "b", "c"), nrow = 4, ncol = 3)
abc

[,1] [,2] [,3]
[1,] a    b    c   
[2,] b    c    a   
[3,] c    a    b   
[4,] a    b    c

In [30]:
# If we want our matrix to fill across rows rather than down columns, we can set byrow = TRUE. For example:
abc_row <- matrix(data = c("a", "b", "c"), nrow = 6, ncol = 6, byrow = TRUE)
abc_row

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] a    b    c    a    b    c   
[2,] a    b    c    a    b    c   
[3,] a    b    c    a    b    c   
[4,] a    b    c    a    b    c   
[5,] a    b    c    a    b    c   
[6,] a    b    c    a    b    c

In [26]:
# We can check the dimensions of a matrix using dim(), which returns the number of rows followed by the number of columns.
dim(abc_row)

[1] 2 3

Here are two matrices (mat1 and mat2) for us to practice some of these methods. Some things we can try are:

* print a matrix
* check the dimensions of the matrix
* subset to certain rows or columns
* replace parts of a matrix
* logical operations
* mathematical operations

Feel free to try out making new matrices as well. Try to get comfortable working with matrices!

In [36]:
mat1 <- matrix(sample(1:100, 16, replace = TRUE), nrow = 4, ncol = 4) 
mat2 <- diag(4)

In [37]:
dim(mat1)

[1] 4 4

In [40]:
mat2

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

# Subsetting within a matrix
Matrices are indexed using brackets with a comma [x,y], where x refers to the rows selected and y refers to the columns selected. For example, test[4,6] will call the value that is in the 4th row and the 6th column of the test matrix.

We can select multiple rows or columns using the following:

In [52]:
# select the 4th through 6th rows and the 1st through 3rd columns
mat1[2:4,1:3]

[,1] [,2] [,3]
[1,] 17   50   21  
[2,] 40    6   87  
[3,] 39   43   11

In [54]:
# select the 4th through 6th rows and ALL of the columns of the matrix
mat1[2:4,]

[,1] [,2] [,3] [,4]
[1,] 17   50   21   73  
[2,] 40    6   87   47  
[3,] 39   43   11   68

In [56]:
# select the 4th AND 6th rows (skipping the 5th) and the 1st through 3rd columns
mat1[c(2,4),1:3]

[,1] [,2] [,3]
[1,] 17   50   21  
[2,] 39   43   11

In [57]:
# select all rows of the 2nd AND 5th columns
mat1[,c(2,4)]

[,1] [,2]
[1,] 33   82  
[2,] 50   73  
[3,]  6   47  
[4,] 43   68

# Linear algebra operations
Let’s say we had a 3-by-3 numeric matrix mat. 
The following code demonstrates performing different linear algebra operations on mat:

In [48]:
## Transpose
t(mat1)
 
## Inverse
solve(mat1)
 
## Matrix multiplication
mat1 %*% t(mat1)
 
## Eigenvalues and Eigenvectors
eig <- eigen(mat1)
   # eig$val are the eigenvalues
   # eig$vec are the eigenvectors

[,1] [,2] [,3] [,4]
[1,] 94   17   40   39  
[2,] 33   50    6   43  
[3,] 66   21   87   11  
[4,] 82   73   47   68

[,1]        [,2]        [,3]        [,4]      
[1,]  0.03861558  0.01816827 -0.02775156 -0.0468888
[2,]  0.15470240  0.22466518 -0.12876061 -0.3387413
[3,]  0.03987460  0.06413589 -0.02131418 -0.1022040
[4,] -0.12642400 -0.16286265  0.10078637  0.2723350

[,1]  [,2]  [,3]  [,4] 
[1,] 21005 10620 13554 11387
[2,] 10620  8559  6238  8008
[3,] 13554  6238 11414  5971
[4,] 11387  8008  5971  8115

In [43]:
# All the rows but only column 2,3, and 4  
mat2[, 2:4]

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 1    0    0   
[3,] 0    1    0   
[4,] 0    0    1

In [45]:
t(mat2)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

In [3]:
# We can create an identity matrix using the diag(x) function where x is the number of elements along the diagonal. 
# x could also be a vector, and the resulting matrix would contain the values of the vector along the diagonal.
# Identity matrix of size 3
diag(3)
 
# Diagonal matrix
diag(c(4,3,2))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 4    0    0   
[2,] 0    3    0   
[3,] 0    0    2

Here are two matrices (mat1 and mat2) for us to practice some of these methods. Some things we can try are:

* print a matrix
* check the dimensions of the matrix
* subset to certain rows or columns
* replace parts of a matrix
* logical operations
* mathematical operations

Feel free to try out making new matrices as well. Try to get comfortable working with matrices!

In [4]:
# Create matrices
mat1 <- matrix(sample(1:100, 16, replace = TRUE), nrow = 4, ncol = 4) 
mat2 <- diag(4)

In [5]:

dim(mat1)


[1] 4 4

In [6]:
mat2

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

# Subsetting within a matrix
Matrices are indexed using brackets with a comma [x,y], where x refers to the rows selected and y refers to the columns selected. For example, test[4,6] will call the value that is in the 4th row and the 6th column of the test matrix.

We can select multiple rows or columns using the following:

In [7]:
# select the 4th through 6th rows and the 1st through 3rd columns
mat1[2:4,1:3]

# select the 4th through 6th rows and ALL of the columns of the matrix
mat1[2:4,]

# select the 4th AND 6th rows (skipping the 5th) and the 1st through 3rd columns
mat1[c(2,4),1:3]

# select all rows of the 2nd AND 5th columns
mat1[,c(2,4)]

[,1] [,2] [,3]
[1,]  71  27   12  
[2,]  87  67   93  
[3,] 100  45   93

[,1] [,2] [,3] [,4]
[1,]  71  27   12   87  
[2,]  87  67   93   90  
[3,] 100  45   93   14

[,1] [,2] [,3]
[1,]  71  27   12  
[2,] 100  45   93

[,1] [,2]
[1,] 44   18  
[2,] 27   87  
[3,] 67   90  
[4,] 45   14

# Linear algebra operations
Let’s say we had a 3-by-3 numeric matrix mat. 
The following code demonstrates performing different linear algebra operations on mat:

In [9]:
## Transpose
t(mat1)
 
## Inverse
solve(mat1)
 
## Matrix multiplication
mat1 %*% t(mat1)
 
## Eigenvalues and Eigenvectors
eig <- eigen(mat1)
   # eig$val are the eigenvalues
   # eig$vec are the eigenvectors

# All the rows but only column 2,3, and 4  
mat2[, 2:4]

t(mat2)

[,1] [,2] [,3] [,4]
[1,] 81   71   87   100 
[2,] 44   27   67    45 
[3,] 17   12   93    93 
[4,] 18   87   90    14

[,1]         [,2]         [,3]         [,4]        
[1,]  0.001386247  0.012514115 -0.014309562  0.012441437
[2,]  0.029049929 -0.026128630  0.023387300 -0.025326066
[3,] -0.014316801 -0.002273988  0.003477042  0.010186114
[4,] -0.008172069  0.009704123  0.003940199 -0.003698524

[,1]  [,2]  [,3]  [,4] 
[1,]  9110  8709 13196 11913
[2,]  8709 13483 16932 10649
[3,] 13196 16932 28807 21624
[4,] 11913 10649 21624 20870

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 1    0    0   
[3,] 0    1    0   
[4,] 0    0    1

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1