## Averages 

In [2]:
# Create Matrix
data_vector <- c(2, 6, 5, 6, 7, 6, 1, 3, 6, 5,
                 6, 5, 4, 8, 4, 7, 4, 4, 3, 3,
                 4, 4, 3, 1, 3, 7, 5, 8, 7, 2)

# Create a matrix with 3 rows and 10 columns
# Change the nrow and ncol arguments to match your desired dimensions
sales <- matrix(data_vector, nrow = 3, ncol = 10, byrow = TRUE)

In [3]:
# Calculate mean
mean(sales)

[1] 4.633333

In [4]:
# Calculate median
median(sales)

[1] 4.5

## Range and Spread

In [5]:
# Minimum value
min(sales)

[1] 1

In [6]:
# Maximum value
max(sales)

[1] 8

In [7]:
# Range of values
range(sales)

[1] 1 8

## Standard Deviation and variance

In [8]:
# Standard deviation
sd(sales)

[1] 1.956128

In [9]:
# Variance
var(sales)

[,1] [,2] [,3] [,4] [,5]       [,6]       [,7]       [,8] [,9]      
 [1,]  4   -1.0 -1.0  2.0 -3.0000000  1.0000000  3.0000000  1.0 -3.0000000
 [2,] -1    1.0  1.0  2.5  2.0000000 -0.5000000 -2.0000000 -2.5 -0.5000000
 [3,] -1    1.0  1.0  2.5  2.0000000 -0.5000000 -2.0000000 -2.5 -0.5000000
 [4,]  2    2.5  2.5 13.0  3.5000000 -0.5000000 -3.5000000 -8.5 -6.5000000
 [5,] -3    2.0  2.0  3.5  4.3333333 -1.1666667 -4.3333333 -4.5  0.1666667
 [6,]  1   -0.5 -0.5 -0.5 -1.1666667  0.3333333  1.1666667  1.0 -0.3333333
 [7,]  3   -2.0 -2.0 -3.5 -4.3333333  1.1666667  4.3333333  4.5 -0.1666667
 [8,]  1   -2.5 -2.5 -8.5 -4.5000000  1.0000000  4.5000000  7.0  3.0000000
 [9,] -3   -0.5 -0.5 -6.5  0.1666667 -0.3333333 -0.1666667  3.0  4.3333333
[10,] -2    1.5  1.5  3.0  3.1666667 -0.8333333 -3.1666667 -3.5 -0.1666667
      [,10]     
 [1,] -2.0000000
 [2,]  1.5000000
 [3,]  1.5000000
 [4,]  3.0000000
 [5,]  3.1666667
 [6,] -0.8333333
 [7,] -3.1666667
 [8,] -3.5000000
 [9,] -0.1666667
[10,]  2.3333333

## Tables

In [13]:
# Print summary table of the sales dataframe
t(summary(sales))

                                                                        
      V1 Min.   :2       1st Qu.:3       Median :4       Mean   :4      
      V2 Min.   :4.0     1st Qu.:4.5     Median :5.0     Mean   :5.0    
      V3 Min.   :3.0     1st Qu.:3.5     Median :4.0     Mean   :4.0    
      V4 Min.   :1.0     1st Qu.:3.5     Median :6.0     Mean   :5.0    
      V5 Min.   :3.000   1st Qu.:3.500   Median :4.000   Mean   :4.667  
      V6 Min.   :6.000   1st Qu.:6.500   Median :7.000   Mean   :6.667  
      V7 Min.   :1.000   1st Qu.:2.500   Median :4.000   Mean   :3.333  
      V8 Min.   :3.0     1st Qu.:3.5     Median :4.0     Mean   :5.0    
      V9 Min.   :3.000   1st Qu.:4.500   Median :6.000   Mean   :5.333  
     V10 Min.   :2.000   1st Qu.:2.500   Median :3.000   Mean   :3.333  
                                        
      V1 3rd Qu.:5       Max.   :6      
      V2 3rd Qu.:5.5     Max.   :6.0    
      V3 3rd Qu.:4.5     Max.   :5.0    
      V4 3rd Qu.:7.0     Max.   :

In [11]:
# Print frequency table
table(sales)

sales
1 2 3 4 5 6 7 8 
2 2 5 6 4 5 4 2 

In [31]:
# The provided data
data_vector <- c(0, 2, 0, 3, 4, 4, 3, 2, 2,
                 1, 0, 2, 2, 2, 0, 2, 2, 0)

# Create a matrix with 2 rows and 9 columns
# Change the nrow and ncol arguments to match your desired dimensions
weekend <- matrix(data_vector, nrow =10, ncol = 3, byrow = TRUE)

# Print the matrix
print(weekend)


Warning message in matrix(data_vector, nrow = 10, ncol = 3, byrow = TRUE):
"data length [18] is not a sub-multiple or multiple of the number of rows [10]"


      [,1] [,2] [,3]
 [1,]    0    2    0
 [2,]    3    4    4
 [3,]    3    2    2
 [4,]    1    0    2
 [5,]    2    2    0
 [6,]    2    2    0
 [7,]    0    2    0
 [8,]    3    4    4
 [9,]    3    2    2
[10,]    1    0    2


In [32]:
# Weekend & sales cross-table
table(weekend, sales)

       sales
weekend 1 2 3 4 5 6 7 8
      0 0 1 1 2 2 1 1 0
      1 0 0 0 0 0 2 0 0
      2 1 1 2 2 1 1 2 2
      3 0 0 1 2 0 1 0 0
      4 1 0 1 0 1 0 1 0

In [26]:
sales

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 2    6    5    6    7    6    1    3    6    5    
[2,] 6    5    4    8    4    7    4    4    3    3    
[3,] 4    4    3    1    3    7    5    8    7    2